# Generated by Django 4.2.16 on 2024-11-22 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_medicamento_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(verbose_name='Tratamiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('medico_responsable', models.CharField(max_length=100, verbose_name='Médico Responsable')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='core.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Certificado Médico',
                'verbose_name_plural': 'Certificados Médicos',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
